//! The one place a `SQLite` row becomes a domain value, and a domain value becomes a bound
//! parameter.
//!
//! `SQLite` has five storage classes and no dedicated timestamp, boolean or JSON type, so every
//! column of those three kinds is encoded on the way in and decoded on the way out. Doing that
//! per query would put the encoding in forty places and guarantee that two of them disagree about
//! the subsecond width, which is the one detail the ordering of the whole outbox rests on.
//!
//! Timestamps are RFC 3339 with a fixed six-digit subsecond and a literal `Z`. The width is fixed
//! rather than minimal because the column is ordered lexicographically: without it,
//! `…:00.5Z` sorts after `…:00.45Z` and a claim returns rows in the wrong order.

use chrono::{DateTime, SecondsFormat, Utc};
use dam_core::{
    Alert, AlertStatus, AmState, Annotations, DedupeKey, Fingerprint, GroupKey, Labels, LabelsHash,
    MatcherSet, NotificationState, Severity,
};
use dam_store::{
    AckKind, Acknowledgement, ChannelId, Effect, ForumTag, GuildId, IgnoreId, IgnoreRule,
    IgnoreScope, Mentions, MessageId, Notification, NotificationId, OutboxId, OutboxItem, Route,
    RouteId, RouteSource, RouteTarget, SilenceLifecycle, SilenceLink, StoreError, Subscription,
    SubscriptionId, UserId, WorkerId,
};
use serde::Serialize;
use serde::de::DeserializeOwned;
use sqlx::Row;
use sqlx::sqlite::SqliteRow;

/// Renders a timestamp for storage.
pub(crate) fn encode_time(value: DateTime<Utc>) -> String {
    value.to_rfc3339_opts(SecondsFormat::Micros, true)
}

/// Renders an optional timestamp for storage.
pub(crate) fn encode_time_opt(value: Option<DateTime<Utc>>) -> Option<String> {
    value.map(encode_time)
}

/// Reads a timestamp back.
fn decode_time(raw: &str, kind: &'static str) -> Result<DateTime<Utc>, StoreError> {
    DateTime::parse_from_rfc3339(raw)
        .map(|value| value.with_timezone(&Utc))
        .map_err(|error| StoreError::Decode {
            kind,
            detail: error.to_string(),
        })
}

/// Reads a timestamp column.
fn time_at(row: &SqliteRow, column: &'static str) -> Result<DateTime<Utc>, StoreError> {
    let raw: String = row.try_get(column).map_err(backend)?;
    decode_time(&raw, column)
}

/// Reads a nullable timestamp column.
fn time_opt_at(row: &SqliteRow, column: &'static str) -> Result<Option<DateTime<Utc>>, StoreError> {
    let raw: Option<String> = row.try_get(column).map_err(backend)?;
    raw.as_deref()
        .map(|raw| decode_time(raw, column))
        .transpose()
}

/// Renders a value as the JSON text a column holds.
///
/// Serialisation of these types cannot fail — they are maps, vectors and enums of owned strings —
/// so a failure here is a bug rather than a condition, and the empty document keeps a bug from
/// also being a write of invalid JSON.
pub(crate) fn encode_json<T: Serialize>(value: &T) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "null".to_owned())
}

/// Reads a JSON column.
fn json_at<T: DeserializeOwned>(row: &SqliteRow, column: &'static str) -> Result<T, StoreError> {
    let raw: String = row.try_get(column).map_err(backend)?;

    serde_json::from_str(&raw).map_err(|error| StoreError::Decode {
        kind: column,
        detail: error.to_string(),
    })
}

/// Reads a nullable JSON column, where null and an absent document mean the same thing.
fn json_opt_at<T: DeserializeOwned>(
    row: &SqliteRow,
    column: &'static str,
) -> Result<Option<T>, StoreError> {
    let raw: Option<String> = row.try_get(column).map_err(backend)?;
    let Some(raw) = raw else {
        return Ok(None);
    };

    serde_json::from_str(&raw).map_err(|error| StoreError::Decode {
        kind: column,
        detail: error.to_string(),
    })
}

/// Reads a column holding one of the domain's stored discriminants.
fn parsed_at<T>(row: &SqliteRow, column: &'static str) -> Result<T, StoreError>
where
    T: std::str::FromStr,
    T::Err: std::fmt::Display,
{
    let raw: String = row.try_get(column).map_err(backend)?;

    raw.parse().map_err(|error: T::Err| StoreError::Decode {
        kind: column,
        detail: error.to_string(),
    })
}

/// Reads a nullable snowflake column into the newtype `wrap` produces.
///
/// The wrapper is passed as a function rather than resolved from a trait, because the newtypes
/// are generated by a macro and share none: asking each of them to implement a trait for this
/// module's benefit would put a decoding concern in the type that carries the id.
fn id_opt_at<T>(
    row: &SqliteRow,
    column: &'static str,
    wrap: fn(i64) -> T,
) -> Result<Option<T>, StoreError> {
    let raw: Option<i64> = row.try_get(column).map_err(backend)?;

    Ok(raw.map(wrap))
}

/// Reads a count column that the domain holds as a `u32`.
///
/// A negative or oversized count is not representable and is clamped rather than refused: the
/// column is a counter the database itself maintains, and failing a read of a whole card because
/// a reply count went strange would hide the card as well as the counter.
fn count_at(row: &SqliteRow, column: &'static str) -> Result<u32, StoreError> {
    let raw: i64 = row.try_get(column).map_err(backend)?;

    Ok(u32::try_from(raw).unwrap_or(0))
}

/// Maps a driver failure onto the store's vocabulary.
///
/// A unique violation is separated out because it is the expected outcome of two workers racing
/// to create one card, and the caller's response to it — re-read and edit the winner's row — is
/// nothing like its response to an unreachable database.
#[expect(
    clippy::needless_pass_by_value,
    reason = "used as a function item in `map_err`, which hands over an owned error; taking a               reference would put a closure at every one of its call sites"
)]
pub(crate) fn backend(error: sqlx::Error) -> StoreError {
    if let sqlx::Error::Database(ref db) = error
        && db.is_unique_violation()
    {
        return StoreError::Conflict {
            // `SQLite` names the columns rather than the index in its message and exposes no
            // constraint name, so the message is the most specific thing available.
            constraint: db.constraint().unwrap_or(db.message()).to_owned(),
        };
    }

    StoreError::Backend {
        detail: error.to_string(),
    }
}

/// Builds an alert and its ledger fields from an `alerts` row.
pub(crate) fn alert_record(row: &SqliteRow) -> Result<dam_store::AlertRecord, StoreError> {
    let fingerprint: String = row.try_get("fingerprint").map_err(backend)?;
    let group_key: Option<String> = row.try_get("group_key").map_err(backend)?;
    let labels_hash: String = row.try_get("labels_hash").map_err(backend)?;

    let alert = Alert {
        fingerprint: Fingerprint::new(fingerprint).map_err(|error| StoreError::Decode {
            kind: "fingerprint",
            detail: error.to_string(),
        })?,
        labels: json_at::<Labels>(row, "labels")?,
        annotations: json_at::<Annotations>(row, "annotations")?,
        starts_at: time_at(row, "starts_at")?,
        ends_at: time_opt_at(row, "ends_at")?,
        generator_url: row.try_get("generator_url").map_err(backend)?,
        status: parsed_at::<AlertStatus>(row, "status")?,
        am_state: parsed_at::<AmState>(row, "am_state")?,
        silenced_by: json_at(row, "silenced_by")?,
        inhibited_by: json_at(row, "inhibited_by")?,
        group_key: group_key.map(GroupKey::new),
    };

    Ok(dam_store::AlertRecord {
        alert,
        labels_hash: LabelsHash::from_stored(labels_hash),
        first_seen_at: time_at(row, "first_seen_at")?,
        last_seen_at: time_at(row, "last_seen_at")?,
        resolved_at: time_opt_at(row, "resolved_at")?,
        flap_count: count_at(row, "flap_count")?,
        episode: count_at(row, "episode")?,
        updated_at: time_at(row, "updated_at")?,
    })
}

/// Builds a card from a `notifications` row.
pub(crate) fn notification(row: &SqliteRow) -> Result<Notification, StoreError> {
    let dedupe_key: String = row.try_get("dedupe_key").map_err(backend)?;
    let route_id: i64 = row.try_get("route_id").map_err(backend)?;
    let guild_id: i64 = row.try_get("guild_id").map_err(backend)?;
    let channel_id: i64 = row.try_get("channel_id").map_err(backend)?;
    let id: i64 = row.try_get("id").map_err(backend)?;

    let fingerprint: String = row.try_get("fingerprint").map_err(backend)?;

    Ok(Notification {
        id: NotificationId::new(id),
        dedupe_key: DedupeKey::from_stored(dedupe_key),
        fingerprint: Fingerprint::new(fingerprint).map_err(|error| StoreError::Decode {
            kind: "notification fingerprint",
            detail: error.to_string(),
        })?,
        route_id: RouteId::new(route_id),
        guild_id: GuildId::from_db(guild_id),
        channel_id: ChannelId::from_db(channel_id),
        message_id: id_opt_at(row, "message_id", MessageId::from_db)?,
        thread_id: id_opt_at(row, "thread_id", ChannelId::from_db)?,
        state: parsed_at::<NotificationState>(row, "state")?,
        render_hash: row.try_get("render_hash").map_err(backend)?,
        applied_tags: json_at(row, "applied_tags")?,
        tags_hash: row.try_get("tags_hash").map_err(backend)?,
        pinned: row.try_get::<i64, _>("pinned").map_err(backend)? != 0,
        archived: row.try_get::<i64, _>("archived").map_err(backend)? != 0,
        responded_at: time_opt_at(row, "responded_at")?,
        escalated_at: time_opt_at(row, "escalated_at")?,
        supersedes: id_opt_at(row, "supersedes", NotificationId::new)?,
        reply_count: count_at(row, "reply_count")?,
        created_at: time_at(row, "created_at")?,
        updated_at: time_at(row, "updated_at")?,
    })
}

/// Builds a queued effect from an `outbox` row.
pub(crate) fn outbox_item(row: &SqliteRow) -> Result<OutboxItem, StoreError> {
    let id: i64 = row.try_get("id").map_err(backend)?;
    let lane: i64 = row.try_get("lane").map_err(backend)?;
    let dedupe_key: String = row.try_get("dedupe_key").map_err(backend)?;
    let claimed_by: Option<String> = row.try_get("claimed_by").map_err(backend)?;

    Ok(OutboxItem {
        id: OutboxId::new(id),
        lane: u16::try_from(lane).unwrap_or(0),
        effect: json_at::<Effect>(row, "payload")?,
        dedupe_key: DedupeKey::from_stored(dedupe_key),
        not_before: time_at(row, "not_before")?,
        attempts: count_at(row, "attempts")?,
        claimed_by: claimed_by.map(WorkerId::new),
        claimed_at: time_opt_at(row, "claimed_at")?,
        last_error: row.try_get("last_error").map_err(backend)?,
        created_at: time_at(row, "created_at")?,
    })
}

/// Builds a route from a `routes` row, compiling its matchers.
///
/// The compiled set is built here rather than on use: evaluating a route against an alert happens
/// once per alert per route, and compiling a regex there would put the regex compiler on the hot
/// path of every notification.
pub(crate) fn route(row: &SqliteRow) -> Result<Route, StoreError> {
    let id: i64 = row.try_get("id").map_err(backend)?;
    let guild_id: i64 = row.try_get("guild_id").map_err(backend)?;
    let matcher_source: String = row.try_get("matcher_source").map_err(backend)?;
    let min_severity: Option<String> = row.try_get("min_severity").map_err(backend)?;

    let matchers = MatcherSet::parse(&matcher_source).map_err(|error| StoreError::Decode {
        kind: "route matchers",
        detail: error.to_string(),
    })?;

    let min_severity = min_severity
        .map(|value| {
            value
                .parse::<Severity>()
                .map_err(|error| StoreError::Decode {
                    kind: "route severity",
                    detail: error.to_string(),
                })
        })
        .transpose()?;

    Ok(Route {
        id: RouteId::new(id),
        guild_id: GuildId::from_db(guild_id),
        name: row.try_get("name").map_err(backend)?,
        matcher_source,
        matchers,
        min_severity,
        target: json_at::<RouteTarget>(row, "target")?,
        group_strategy: parsed_at::<dam_store::GroupStrategy>(row, "group_strategy")?,
        mentions: json_at::<Mentions>(row, "mentions")?,
        escalation: json_opt_at::<dam_store::Escalation>(row, "escalation")?,
        priority: row
            .try_get::<i64, _>("priority")
            .map_err(backend)?
            .try_into()
            .unwrap_or(i32::MAX),
        continue_to_next: row.try_get::<i64, _>("continue_to_next").map_err(backend)? != 0,
        source: parsed_at::<RouteSource>(row, "source")?,
        enabled: row.try_get::<i64, _>("enabled").map_err(backend)? != 0,
        created_by: id_opt_at(row, "created_by", UserId::from_db)?,
        created_at: time_at(row, "created_at")?,
    })
}

/// Builds an ignore rule from an `ignore_rules` row, compiling its matchers.
pub(crate) fn ignore_rule(row: &SqliteRow) -> Result<IgnoreRule, StoreError> {
    let id: i64 = row.try_get("id").map_err(backend)?;
    let guild_id: i64 = row.try_get("guild_id").map_err(backend)?;
    let created_by: i64 = row.try_get("created_by").map_err(backend)?;
    let matcher_source: String = row.try_get("matcher_source").map_err(backend)?;

    let matchers = MatcherSet::parse(&matcher_source).map_err(|error| StoreError::Decode {
        kind: "ignore matchers",
        detail: error.to_string(),
    })?;

    Ok(IgnoreRule {
        id: IgnoreId::new(id),
        scope: parsed_at::<IgnoreScope>(row, "scope")?,
        guild_id: GuildId::from_db(guild_id),
        channel_id: id_opt_at(row, "channel_id", ChannelId::from_db)?,
        matcher_source,
        matchers,
        reason: row.try_get("reason").map_err(backend)?,
        created_by: UserId::from_db(created_by),
        created_at: time_at(row, "created_at")?,
        expires_at: time_opt_at(row, "expires_at")?,
        revoked_at: time_opt_at(row, "revoked_at")?,
    })
}

/// Builds a silence link from a `silences` row.
pub(crate) fn silence_link(row: &SqliteRow) -> Result<SilenceLink, StoreError> {
    Ok(SilenceLink {
        am_id: row.try_get("am_id").map_err(backend)?,
        matchers: row.try_get("matchers").map_err(backend)?,
        starts_at: time_at(row, "starts_at")?,
        ends_at: time_at(row, "ends_at")?,
        created_by: row.try_get("created_by").map_err(backend)?,
        discord_user_id: id_opt_at(row, "discord_user_id", UserId::from_db)?,
        origin_message: row.try_get("origin_message").map_err(backend)?,
        comment: row.try_get("comment").map_err(backend)?,
        state: parsed_at::<SilenceLifecycle>(row, "state")?,
        synced_at: time_at(row, "synced_at")?,
    })
}

/// Builds a cached forum tag from a `forum_tags` row.
pub(crate) fn forum_tag(row: &SqliteRow) -> Result<ForumTag, StoreError> {
    let channel_id: i64 = row.try_get("channel_id").map_err(backend)?;
    let tag_id: i64 = row.try_get("tag_id").map_err(backend)?;

    Ok(ForumTag {
        channel_id: ChannelId::from_db(channel_id),
        name: row.try_get("tag_name").map_err(backend)?,
        id: dam_store::TagId::from_db(tag_id),
        moderated: row.try_get::<i64, _>("moderated").map_err(backend)? != 0,
        synced_at: time_at(row, "synced_at")?,
    })
}

/// Builds a subscription from a `subscriptions` row, compiling its matchers.
pub(crate) fn subscription(row: &SqliteRow) -> Result<Subscription, StoreError> {
    let id: i64 = row.try_get("id").map_err(backend)?;
    let user_id: i64 = row.try_get("user_id").map_err(backend)?;
    let matcher_source: String = row.try_get("matcher_source").map_err(backend)?;

    let matchers = MatcherSet::parse(&matcher_source).map_err(|error| StoreError::Decode {
        kind: "subscription matchers",
        detail: error.to_string(),
    })?;

    Ok(Subscription {
        id: SubscriptionId::new(id),
        user_id: UserId::from_db(user_id),
        matcher_source,
        matchers,
        min_severity: severity_opt_at(row, "min_severity", "subscription severity")?,
        created_at: time_at(row, "created_at")?,
    })
}

/// Reads a nullable severity column.
fn severity_opt_at(
    row: &SqliteRow,
    column: &'static str,
    kind: &'static str,
) -> Result<Option<Severity>, StoreError> {
    let raw: Option<String> = row.try_get(column).map_err(backend)?;

    raw.map(|value| {
        value
            .parse::<Severity>()
            .map_err(|error| StoreError::Decode {
                kind,
                detail: error.to_string(),
            })
    })
    .transpose()
}

/// Builds the live acknowledgement from an `acknowledgements` row.
pub(crate) fn acknowledgement(row: &SqliteRow) -> Result<Acknowledgement, StoreError> {
    let user_id: i64 = row.try_get("user_id").map_err(backend)?;

    Ok(Acknowledgement {
        user_id: UserId::from_db(user_id),
        kind: parsed_at::<AckKind>(row, "kind")?,
        note: row.try_get("note").map_err(backend)?,
        at: time_at(row, "created_at")?,
    })
}
