//! Build tooling: regenerates the checked-query caches and the configuration reference.
//!
//! Two jobs, and both exist for the same reason: a generated artefact is committed, and a change
//! that would alter it must fail in review rather than drift. The commands here produce those
//! artefacts, and continuous integration runs them and asserts nothing moved.
//!
//! ```bash
//! cargo xtask db-prepare      # regenerate both .sqlx offline caches
//! cargo xtask config-docs     # regenerate docs/config.md, docs/config.json, config.example.toml
//! ```

use std::env;
use std::ffi::OsStr;
use std::path::{Path, PathBuf};
use std::process::Stdio;

use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use testcontainers::runners::AsyncRunner;
use testcontainers_modules::postgres::Postgres;
use tokio::process::Command;

/// Crate holding the `PostgreSQL` backend and its offline cache.
const POSTGRES_CRATE: &str = "discord-alertmanager-store-postgres";

/// Crate holding the `SQLite` backend and its offline cache.
const SQLITE_CRATE: &str = "discord-alertmanager-store-sqlite";

/// Opens `docs/config.md`, which the schema renderer emits as two bare tables.
///
/// The tables are the document, and a document whose first line is a table header has no title and
/// no summary for anything that indexes it. The README's documentation table is built by walking
/// `docs/`, so without these lines it renders a row whose purpose column is a row of column names.
/// The banner is an HTML comment because that is what every generated file in this estate opens
/// with, and what the indexer knows to skip.
const CONFIG_REFERENCE_PREAMBLE: &str = "<!--
Generated by `cargo xtask config-docs` from the types in crates/discord-alertmanager-config.
Edit those types, not this file.
-->

# Configuration reference

Every key the service reads, and the variables that decide where those keys come from.

The first table is the loader. Its variables are read straight from the environment, before there
is a configuration to describe them, so no file can supply one. The second table is every key the
layers fill: the TOML file, the `DAM_`-prefixed environment, a secrets directory, and `_FILE`
indirection, in that order of precedence.

";

/// Build tooling for this workspace.
#[derive(Debug, Parser)]
#[command(name = "xtask", about = "Build tooling for discord-alertmanager")]
struct Cli {
    /// What to do.
    #[command(subcommand)]
    command: Task,
}

/// The jobs this tool performs.
#[derive(Debug, Subcommand)]
enum Task {
    /// Regenerates the `sqlx` offline caches for both backends.
    ///
    /// Starts a throwaway `PostgreSQL` container and creates a temporary `SQLite` file, applies
    /// each backend's migrations to its own database, and asks `sqlx` to record every checked
    /// query against the resulting schema.
    DbPrepare,

    /// Regenerates the configuration reference, the JSON schema and the example file.
    ConfigDocs,
}

#[tokio::main]
async fn main() -> Result<()> {
    match Cli::parse().command {
        Task::DbPrepare => db_prepare().await,
        Task::ConfigDocs => config_docs().await,
    }
}

/// Regenerates both offline caches.
///
/// The container belongs here rather than in a build script. Starting one from `build.rs` would
/// make every build require a container runtime, break cross-compilation and offline builds, and
/// turn a cold cache into an image pull — for a schema that changes only when a migration does.
async fn db_prepare() -> Result<()> {
    let root = workspace_root()?;

    let postgres = Postgres::default()
        .start()
        .await
        .context("starting a PostgreSQL container")?;
    let port = postgres
        .get_host_port_ipv4(5432)
        .await
        .context("reading the container's mapped port")?;
    let postgres_url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");

    prepare(&root, POSTGRES_CRATE, &postgres_url).await?;

    // A file rather than `:memory:`: the schema has to outlive the connection that migrates it,
    // and `sqlx prepare` opens its own.
    let sqlite_path = env::temp_dir().join(format!("dam-prepare-{}.db", std::process::id()));
    let sqlite_url = format!(
        "sqlite://{}?mode=rwc",
        sqlite_path.to_string_lossy().replace('\\', "/")
    );

    let result = prepare(&root, SQLITE_CRATE, &sqlite_url).await;

    // Removed whether or not the preparation succeeded, so a failed run does not leave a stale
    // database that the next one would silently reuse.
    let _ = std::fs::remove_file(&sqlite_path);
    result?;

    println!("offline caches regenerated for both backends");
    Ok(())
}

/// Applies one backend's migrations and records its checked queries.
async fn prepare(root: &Path, crate_name: &str, database_url: &str) -> Result<()> {
    let migrations = root.join("crates").join(crate_name).join("migrations");

    if !migrations.is_dir() {
        bail!(
            "{crate_name} has no migrations directory at {}",
            migrations.display()
        );
    }

    run(
        root,
        "cargo",
        [
            "sqlx",
            "migrate",
            "run",
            "--source",
            &migrations.to_string_lossy(),
            "--database-url",
            database_url,
        ],
        // `SQLX_OFFLINE` is pinned to true for the whole workspace, and both of these commands
        // are the one place that must reach a live database instead.
        &[("SQLX_OFFLINE", "false"), ("DATABASE_URL", database_url)],
    )
    .await
    .with_context(|| format!("applying {crate_name} migrations"))?;

    run(
        root,
        "cargo",
        ["sqlx", "prepare", "-p", crate_name],
        &[("SQLX_OFFLINE", "false"), ("DATABASE_URL", database_url)],
    )
    .await
    .with_context(|| format!("recording {crate_name} queries"))
}

/// Regenerates the three files that describe the configuration surface.
async fn config_docs() -> Result<()> {
    let root = workspace_root()?;
    let docs = root.join("docs");
    std::fs::create_dir_all(&docs).context("creating the docs directory")?;

    let outputs = [
        ("markdown", docs.join("config.md"), CONFIG_REFERENCE_PREAMBLE),
        ("json-schema", docs.join("config.json"), ""),
        // The TOML renderer writes its own banner, and a JSON document cannot carry one.
        ("toml", root.join("config.example.toml"), ""),
    ];

    for (format, path, preamble) in outputs {
        let rendered = capture(
            &root,
            "cargo",
            [
                "run",
                "--quiet",
                "-p",
                "discord-alertmanager-config",
                "--features",
                "config-schema",
                "--example",
                "config-schema",
                "--",
                "--format",
                format,
            ],
        )
        .await
        .with_context(|| format!("generating {}", path.display()))?;

        let mut contents = preamble.as_bytes().to_vec();
        contents.extend_from_slice(&rendered);

        std::fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;

        println!("wrote {}", path.display());
    }

    Ok(())
}

/// Runs a command in the workspace root, inheriting its output.
///
/// Output is inherited rather than captured because the interesting failures — a migration that
/// does not apply, a query that no longer type-checks — are already well explained by the tool
/// that produced them, and re-wrapping them only buries the message.
async fn run<I, S>(root: &Path, program: &str, args: I, env: &[(&str, &str)]) -> Result<()>
where
    I: IntoIterator<Item = S>,
    S: AsRef<OsStr>,
{
    let mut command = Command::new(program);
    command
        .current_dir(root)
        .args(args)
        .stdin(Stdio::null())
        .kill_on_drop(true);

    for (key, value) in env {
        command.env(key, value);
    }

    let status = command
        .status()
        .await
        .with_context(|| format!("running {program}"))?;

    if !status.success() {
        bail!("{program} exited with {status}");
    }

    Ok(())
}

/// Runs a command in the workspace root and returns what it printed.
///
/// The generator writes its rendering to standard output, which is the right interface for a tool
/// that also gets piped into a diff by hand. Capturing it here and writing the file is what keeps
/// a half-written artefact from being left behind when the generator fails partway.
async fn capture<I, S>(root: &Path, program: &str, args: I) -> Result<Vec<u8>>
where
    I: IntoIterator<Item = S>,
    S: AsRef<OsStr>,
{
    let output = Command::new(program)
        .current_dir(root)
        .args(args)
        .stdin(Stdio::null())
        .stderr(Stdio::inherit())
        .kill_on_drop(true)
        .output()
        .await
        .with_context(|| format!("running {program}"))?;

    if !output.status.success() {
        bail!("{program} exited with {}", output.status);
    }

    Ok(output.stdout)
}

/// The workspace root, derived from this crate's manifest rather than from the current directory.
///
/// `cargo xtask` can be invoked from anywhere in the tree, and every path here is relative to the
/// root; resolving it from the manifest is what makes the command work the same from a crate
/// subdirectory as from the top.
fn workspace_root() -> Result<PathBuf> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    manifest
        .parent()
        .map(Path::to_path_buf)
        .context("locating the workspace root from the xtask manifest")
}
